### ISSUE TITLE
Suggestion: Pay to fly

### ISSUE THREAD

**Issue by regret** [Radi3nt/Fly-plugin#1]
Are you able to implement charging players to fly? I think it could be a cool addition to the plugin to charge players if they want access to temporarily flying. They pay by the minute, hour, or whatever.

**Comment by Radi3nt** [comment]
Hello,

This could be a good idea, but it's too specific. I can do this but if servers just want to have a fly and give it to players **manually** they don't want players to toggle their fly with a charging ability. So I can make an add-on for this, but adding this feature in the main plugin is not a good idea. Plugins must be extensible. Going into a too specific way is not something good. If you have an idea how to adapt your suggestion to be less specific, I think I'm going to add it.

Thanks for your time,
Radi3nt

**Comment by regret** [comment]
An add-on does make more sense for this, I’m sorry about that

**Comment by Radi3nt** [comment]
No worrys, I’m going to make one !

**Comment by Radi3nt** [comment]
Contact me by discord for more infos (go on spigot, there’s the link)

**Comment by Radi3nt** [comment]
#### Hey ! Remember me ?

I’m working on the add on, if your still interested please contact me again. 
My discord and mail are in the readme.
:)

Best regards,
Radi3nt

**Comment by Radi3nt** [comment]
Hi !

You can do this with an external plugin like luckperm. My plugin is compatible with a permission like: "fly.tempfly.500". The player can fly under 500 second. So you just have to manage that when you enter the command, it remove you this permission. It's possible with luckperm. I advice to wait for the 3.0.0 update, because in the older version, this feature has many bugs.
Don't worry, you won't have to wait to long for this version. I'm working on it !

Best regards,
Radi3nt
